# Generated by Django 5.0 on 2024-07-12 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Введите место, где необходимо выполнять привычку",
                        max_length=200,
                        verbose_name="Место выполнения привычки",
                    ),
                ),
                (
                    "time",
                    models.CharField(
                        choices=[
                            ("morning", "утром"),
                            ("day", "днем"),
                            ("evening", "вечером"),
                            ("anytime", "в любое время"),
                        ],
                        help_text="Укажите время, в которое необходимо выполнять привычку",
                        max_length=20,
                        verbose_name="Время выполнения привычки",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Опишите, что необходимо сделать",
                        verbose_name="Описание привычки",
                    ),
                ),
                (
                    "is_pleasant_habit",
                    models.BooleanField(
                        help_text="Выберите, является ли эта привычка приятной",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "ежедневно"),
                            ("every two days", "раз в два дня"),
                            ("every three days", "раз в три дня"),
                            ("every four days", "раз в четыре дня"),
                            ("every five days", "раз в пять дней"),
                            ("every six days", "раз в шесть дней"),
                            ("weekly", "раз в неделю"),
                        ],
                        default="daily",
                        help_text="Укажите период, в котором необходимо выполнять привычку",
                        max_length=20,
                        verbose_name="Период выполнения привычки",
                    ),
                ),
                (
                    "award",
                    models.TextField(
                        help_text="Введите вознаграждение за выполнение полезной привычки",
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveIntegerField(
                        help_text="Введите время в секундах на выполнение привычки, до 120 сек",
                        verbose_name="Время на выполнение привычки",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        help_text="Выберите, является ли привычка публичной",
                        verbose_name="Признак публичной привычки",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель привычки",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите приятную привычку за выполнение полезной",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
