# Generated by Django 5.0 on 2024-07-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="award",
            field=models.TextField(
                blank=True,
                help_text="Введите вознаграждение за выполнение полезной привычки",
                null=True,
                verbose_name="Вознаграждение",
            ),
        ),
    ]
