# Generated by Django 5.0 on 2024-07-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_award"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="period",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Укажите периодичность выполнения привычки в днях, не более недели",
                verbose_name="Периодичность",
            ),
        ),
    ]
