# Generated by Django 5.0 on 2024-07-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="period",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Введите периуд выполнения привычки, в днях, не больше 7 дней",
                verbose_name="Периодичность выполнения",
            ),
        ),
    ]
